# Generated by Django 2.0.7 on 2018-07-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('source', models.URLField(max_length=2000)),
                ('profile', models.CharField(choices=[('kindle', 'Kindle 201..'), ('kindle_dx', 'Kindle DX'), ('kindle_fire', 'Kindle Fire'), ('kindle_oasis', 'Kindle Oasis 1,2'), ('kindle_pw', 'Kindle Paperwhite 1,2'), ('kindle_pw3', 'Kindle Paperwhite 3'), ('kindle_voyage', 'Kindle Voyage')], default='kindle_pw3', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
